### ISSUE TITLE
Tracking WordPress issues

### ISSUE THREAD

**Issue by marekdedic** [skaut/phan-wordpress-stubs#1]
- [x] https://core.trac.wordpress.org/ticket/48343
- [x] https://core.trac.wordpress.org/ticket/48344
- [x] https://core.trac.wordpress.org/ticket/48346
- [x] https://core.trac.wordpress.org/ticket/48347
- [x] https://core.trac.wordpress.org/ticket/48348
- [x] https://core.trac.wordpress.org/ticket/48349
- [x] https://core.trac.wordpress.org/ticket/48350
- [x] https://core.trac.wordpress.org/ticket/48351
- [x] https://core.trac.wordpress.org/ticket/48352
- [x] https://core.trac.wordpress.org/ticket/48353
- [x] https://core.trac.wordpress.org/ticket/48354

Docs tracking issue for 5.4: https://core.trac.wordpress.org/ticket/48303
Docs tracking issue for 5.5: https://core.trac.wordpress.org/ticket/49572
